// let x;
// console.log(x);
// x = 7;
let x = 7;
x = 6;
x = 5;
x = 4; 
// let x = 8;
let y= 3;
let z= x + y;
console.log('Answer: ' + z);
let firstNumber = 7;
let secondNumber = 3;
let firstName = 'Bob';
let zipCode = '75082';
